apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-openmetadata-configs
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cfs-shared-sc
  resources:
    requests:
      storage: 1Gi
