apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-extreme-rwx-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-nas-extreme-rwx
  resources:
    requests:
      storage: 100Gi